#!/bin/bash
set -e

sudo apt update -y
sudo apt install -y openjdk-17-jdk curl

# get latest version dynamically
LATEST=$(curl -s https://get.jenkins.io/debian-stable/ | grep -oP 'jenkins_\K[0-9.]+(?=_all.deb)' | sort -V | tail -1)

wget https://get.jenkins.io/debian-stable/jenkins_${LATEST}_all.deb

sudo apt install -y ./jenkins_${LATEST}_all.deb

sudo systemctl start jenkins
sudo systemctl enable jenkins

sudo cat /var/lib/jenkins/secrets/initialAdminPassword

=====================================================

# try this first
docker run -d -p 8080:8080 -p 50000:50000 jenkins/jenkins:lts
-------------------- or ----------------------
#second one
docker run -d -p 8080:8080 -p 50000:50000 jenkins/jenkins:lts
-------------------- or ----------------------
Step 1: Download Jenkins manually
wget https://pkg.jenkins.io/debian-stable/binary/jenkins_2.452.3_all.deb
Step 2: Install it
sudo apt install -y ./jenkins_2.452.3_all.deb
Step 3: Start Jenkins
sudo systemctl start jenkins
sudo systemctl enable jenkins
Step 4: Check status
sudo systemctl status jenkins
Step 5: Get password
sudo cat /var/lib/jenkins/secrets/initialAdminPassword
