#!/bin/bash
set -e

echo "===== Update system ====="
sudo apt update -y

echo "===== Install Java ====="
sudo apt install -y openjdk-17-jdk

echo "===== Download latest Jenkins ====="
wget https://pkg.jenkins.io/debian-stable/binary/jenkins_latest_all.deb

echo "===== Install Jenkins ====="
sudo apt install -y ./jenkins_latest_all.deb

echo "===== Start Jenkins ====="
sudo systemctl start jenkins
sudo systemctl enable jenkins

echo "===== Jenkins Status ====="
sudo systemctl status jenkins --no-pager

echo "===== Jenkins Password ====="
sudo cat /var/lib/jenkins/secrets/initialAdminPassword

=======================================================

# try this first
docker run -d -p 8080:8080 -p 50000:50000 jenkins/jenkins:lts
-------------------- or ----------------------
#second one
docker run -d -p 8080:8080 -p 50000:50000 jenkins/jenkins:lts
-------------------- or ----------------------
Step 1: Download Jenkins manually
wget https://pkg.jenkins.io/debian-stable/binary/jenkins_2.452.3_all.deb
Step 2: Install it
sudo apt install -y ./jenkins_2.452.3_all.deb
Step 3: Start Jenkins
sudo systemctl start jenkins
sudo systemctl enable jenkins
Step 4: Check status
sudo systemctl status jenkins
Step 5: Get password
sudo cat /var/lib/jenkins/secrets/initialAdminPassword
